version: '3.8'

services:
  backend:
    image: brunohznd/reuniao-backend:latest
    networks:
      - Marbrnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reuniao-backend.rule=Host(`reuniao.automacao.marbr.com.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.reuniao-backend.service=reuniao-backend-svc"
      - "traefik.http.middlewares.reuniao-api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.reuniao-backend.middlewares=reuniao-api-stripprefix"
      - "traefik.http.services.reuniao-backend-svc.loadbalancer.server.port=3001"

  frontend:
    image: brunohznd/reuniao-frontend:latest
    networks:
      - Marbrnet
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reuniao-frontend.rule=Host(`reuniao.automacao.marbr.com.br`)"
      - "traefik.http.routers.reuniao-frontend.service=reuniao-frontend-svc"
      - "traefik.http.services.reuniao-frontend-svc.loadbalancer.server.port=3000"

networks:
  Marbrnet: # Define a rede como externa, pois ela já foi criada pelo Traefik
    external: true
